[build]
  command = "node netlify-build.js"
  publish = "dist"

# Redirect API requests to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Handle SPA routing - must be after API redirects
[[redirects]]
  from = "/*"
  to = "/client/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  
[build.environment]
  NODE_VERSION = "18"